
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "i686")

set(TRIPLE_TARGET "i686-linux-gnu")

set(CMAKE_C_COMPILER "${TRIPLE_TARGET}-gcc")
set(CMAKE_CXX_COMPILER "${TRIPLE_TARGET}-g++")

set(CMAKE_FIND_ROOT_PATH "/usr/i686-linux-gnu")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

