/*-
 * Copyright (c) 2023, Collin Funk
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#include <config.h>

#include <inttypes.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "int-overflow.h"
#include "test-help.h"

/* Defined for readability in tests. */
#undef UINT_MIN
#define UINT_MIN 0U

static void test_type_max_unsigned (void);
static void test_type_min_unsigned (void);
static void test_type_max_signed (void);
static void test_type_min_signed (void);
static void test_type_is_signed (void);
static void test_type_is_unsigned (void);
static void test_int_add_range_overflow (void);
static void test_int_sub_range_overflow (void);
static void test_int_mul_range_overflow (void);
static void test_int_div_range_overflow (void);

int
main (void)
{
  test_type_max_unsigned ();
  test_type_min_unsigned ();
  test_type_max_signed ();
  test_type_min_signed ();
  test_type_is_signed ();
  test_type_is_unsigned ();
  test_int_add_range_overflow ();
  test_int_sub_range_overflow ();
  test_int_mul_range_overflow ();
  test_int_div_range_overflow ();
  return 0;
}

static void
test_type_max_unsigned (void)
{
  ASSERT (TYPE_MAX_UNSIGNED (unsigned char) == UCHAR_MAX);
  ASSERT (TYPE_MAX_UNSIGNED (unsigned short int) == USHRT_MAX);
  ASSERT (TYPE_MAX_UNSIGNED (unsigned int) == UINT_MAX);
  ASSERT (TYPE_MAX_UNSIGNED (unsigned long int) == ULONG_MAX);
  ASSERT (TYPE_MAX_UNSIGNED (unsigned long long int) == ULLONG_MAX);
}

static void
test_type_min_unsigned (void)
{
  ASSERT (TYPE_MIN_UNSIGNED (unsigned char) == 0);
  ASSERT (TYPE_MIN_UNSIGNED (unsigned short int) == 0);
  ASSERT (TYPE_MIN_UNSIGNED (unsigned int) == 0);
  ASSERT (TYPE_MIN_UNSIGNED (unsigned long int) == 0);
  ASSERT (TYPE_MIN_UNSIGNED (unsigned long long int) == 0);
}

static void
test_type_max_signed (void)
{
  ASSERT (TYPE_MAX_SIGNED (signed char) == CHAR_MAX);
  ASSERT (TYPE_MAX_SIGNED (short int) == SHRT_MAX);
  ASSERT (TYPE_MAX_SIGNED (int) == INT_MAX);
  ASSERT (TYPE_MAX_SIGNED (long int) == LONG_MAX);
  ASSERT (TYPE_MAX_SIGNED (long long int) == LLONG_MAX);
}

static void
test_type_min_signed (void)
{
  ASSERT (TYPE_MIN_SIGNED (signed char) == CHAR_MIN);
  ASSERT (TYPE_MIN_SIGNED (short int) == SHRT_MIN);
  ASSERT (TYPE_MIN_SIGNED (int) == INT_MIN);
  ASSERT (TYPE_MIN_SIGNED (long int) == LONG_MIN);
  ASSERT (TYPE_MIN_SIGNED (long long int) == LLONG_MIN);
}

static void
test_type_is_signed (void)
{
  ASSERT (TYPE_IS_SIGNED (signed char));
  ASSERT (TYPE_IS_SIGNED (short int));
  ASSERT (TYPE_IS_SIGNED (int));
  ASSERT (TYPE_IS_SIGNED (long int));
  ASSERT (TYPE_IS_SIGNED (long long int));
  ASSERT (!TYPE_IS_SIGNED (unsigned char));
  ASSERT (!TYPE_IS_SIGNED (unsigned short int));
  ASSERT (!TYPE_IS_SIGNED (unsigned int));
  ASSERT (!TYPE_IS_SIGNED (unsigned long int));
  ASSERT (!TYPE_IS_SIGNED (unsigned long long int));
}

static void
test_type_is_unsigned (void)
{
  ASSERT (!TYPE_IS_UNSIGNED (signed char));
  ASSERT (!TYPE_IS_UNSIGNED (short int));
  ASSERT (!TYPE_IS_UNSIGNED (int));
  ASSERT (!TYPE_IS_UNSIGNED (long int));
  ASSERT (!TYPE_IS_UNSIGNED (long long int));
  ASSERT (TYPE_IS_UNSIGNED (unsigned char));
  ASSERT (TYPE_IS_UNSIGNED (unsigned short int));
  ASSERT (TYPE_IS_UNSIGNED (unsigned int));
  ASSERT (TYPE_IS_UNSIGNED (unsigned long int));
  ASSERT (TYPE_IS_UNSIGNED (unsigned long long int));
}

static void
test_int_add_range_overflow (void)
{
  /* No overflow. */
  ASSERT (!INT_ADD_RANGE_OVERFLOW (INT_MIN, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (INT_MAX, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (INT_MIN, 1, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (INT_MAX, -1, INT_MIN, INT_MAX));
  /* a + b == b + a */
  ASSERT (!INT_ADD_RANGE_OVERFLOW (0, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (0, INT_MAX, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (1, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (-1, INT_MAX, INT_MIN, INT_MAX));

  /* Overflow. */
  ASSERT (INT_ADD_RANGE_OVERFLOW (INT_MIN, -1, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (INT_MAX, 1, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (INT_MIN, -2, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (INT_MAX, 2, INT_MIN, INT_MAX));
  /* a + b == b + a */
  ASSERT (INT_ADD_RANGE_OVERFLOW (-1, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (1, INT_MAX, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (-2, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (2, INT_MAX, INT_MIN, INT_MAX));

  /* No overflow. */
  ASSERT (!INT_ADD_RANGE_OVERFLOW (UINT_MIN, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (UINT_MAX, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (UINT_MIN, 1, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (UINT_MAX, -1, UINT_MIN, UINT_MAX));
  /* a + b == b + a */
  ASSERT (!INT_ADD_RANGE_OVERFLOW (0, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (0, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (1, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (-1, UINT_MAX, UINT_MIN, UINT_MAX));

  /* Overflow. */
  ASSERT (INT_ADD_RANGE_OVERFLOW (UINT_MIN, -1, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (UINT_MAX, 1, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (UINT_MIN, -2, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (UINT_MAX, 2, UINT_MIN, UINT_MAX));
  /* a + b == b + a */
  ASSERT (INT_ADD_RANGE_OVERFLOW (-1, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (1, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (-2, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (2, UINT_MAX, UINT_MIN, UINT_MAX));
}

static void
test_int_sub_range_overflow (void)
{
  /* No overflow. */
  ASSERT (!INT_SUB_RANGE_OVERFLOW (INT_MIN, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (INT_MAX, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (INT_MIN, -1, INT_MIN, INT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (INT_MAX, 1, INT_MIN, INT_MAX));

  /* Overflow. */
  ASSERT (INT_SUB_RANGE_OVERFLOW (INT_MIN, 1, INT_MIN, INT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (INT_MAX, -1, INT_MIN, INT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (INT_MIN, 2, INT_MIN, INT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (INT_MAX, -2, INT_MIN, INT_MAX));

  /* No overflow. */
  ASSERT (!INT_SUB_RANGE_OVERFLOW (UINT_MIN, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (UINT_MAX, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (UINT_MIN, -1, UINT_MIN, UINT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (UINT_MAX, 1, UINT_MIN, UINT_MAX));

  /* Overflow. */
  ASSERT (INT_SUB_RANGE_OVERFLOW (UINT_MIN, 1, UINT_MIN, UINT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (UINT_MAX, -1, UINT_MIN, UINT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (UINT_MIN, 2, UINT_MIN, UINT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (UINT_MAX, -2, UINT_MIN, UINT_MAX));
}

static void
test_int_mul_range_overflow (void)
{
  /* No overflow. */
  ASSERT (!INT_MUL_RANGE_OVERFLOW (INT_MIN, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (INT_MAX, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (INT_MIN, 1, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (INT_MAX, 1, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (INT_MIN + 1, -1, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (INT_MAX, -1, INT_MIN, INT_MAX));
  /* a * b == b * a */
  ASSERT (!INT_MUL_RANGE_OVERFLOW (0, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (0, INT_MAX, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (1, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (1, INT_MAX, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (-1, INT_MIN + 1, INT_MIN, INT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (-1, INT_MAX, INT_MIN, INT_MAX));

  /* Overflow. */
  ASSERT (INT_MUL_RANGE_OVERFLOW (INT_MIN, 2, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (INT_MAX, 2, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (INT_MIN, 3, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (INT_MAX, 3, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (INT_MIN, -1, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (INT_MAX, -2, INT_MIN, INT_MAX));

  /* a * b == b * a */
  ASSERT (INT_MUL_RANGE_OVERFLOW (2, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (2, INT_MAX, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (3, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (3, INT_MAX, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (-1, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (-2, INT_MAX, INT_MIN, INT_MAX));

  /* No overflow. */
  ASSERT (!INT_MUL_RANGE_OVERFLOW (UINT_MIN, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (UINT_MAX, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (UINT_MIN, 1, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (UINT_MAX, 1, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (UINT_MIN, 2, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (UINT_MIN, 3, UINT_MIN, UINT_MAX));
  /* a * b == b * a */
  ASSERT (!INT_MUL_RANGE_OVERFLOW (0, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (0, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (1, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (1, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (2, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (!INT_MUL_RANGE_OVERFLOW (3, UINT_MIN, UINT_MIN, UINT_MAX));

  /* Overflow. */
  ASSERT (INT_MUL_RANGE_OVERFLOW (UINT_MAX, 2, UINT_MIN, UINT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (UINT_MAX, 3, UINT_MIN, UINT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (UINT_MAX, -1, UINT_MIN, UINT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (UINT_MAX, -2, UINT_MIN, UINT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (UINT_MAX, -3, UINT_MIN, UINT_MAX));
  /* a * b == b * a */
  ASSERT (INT_MUL_RANGE_OVERFLOW (2, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (3, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (-1, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (-2, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (INT_MUL_RANGE_OVERFLOW (-3, UINT_MAX, UINT_MIN, UINT_MAX));
}

static void
test_int_div_range_overflow (void)
{
  /* No overflow. */
  ASSERT (!INT_DIV_RANGE_OVERFLOW (INT_MIN, 1, INT_MIN, INT_MAX));
  ASSERT (!INT_DIV_RANGE_OVERFLOW (INT_MAX, 1, INT_MIN, INT_MAX));
  ASSERT (!INT_DIV_RANGE_OVERFLOW (INT_MAX, -1, INT_MIN, INT_MAX));

  /* Overflow. */
  ASSERT (INT_DIV_RANGE_OVERFLOW (INT_MIN, 0, INT_MIN, INT_MAX));
  ASSERT (INT_DIV_RANGE_OVERFLOW (INT_MAX, 0, INT_MIN, INT_MAX));
  ASSERT (INT_DIV_RANGE_OVERFLOW (INT_MIN, -1, INT_MIN, INT_MAX));

  /* No overflow. */
  ASSERT (!INT_DIV_RANGE_OVERFLOW (UINT_MIN, 1, UINT_MIN, UINT_MAX));
  ASSERT (!INT_DIV_RANGE_OVERFLOW (UINT_MAX, 1, UINT_MIN, UINT_MAX));
  ASSERT (!INT_DIV_RANGE_OVERFLOW (UINT_MIN, -1, UINT_MIN, UINT_MAX));

  ASSERT (INT_DIV_RANGE_OVERFLOW (UINT_MIN, 0, UINT_MIN, UINT_MAX));
  ASSERT (INT_DIV_RANGE_OVERFLOW (UINT_MIN, 0, UINT_MIN, UINT_MAX));
  ASSERT (INT_DIV_RANGE_OVERFLOW (UINT_MAX, -1, UINT_MIN, UINT_MAX));
}
