/*-
 * Copyright (c) 2023, Collin Funk
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "int-overflow.h"
#include "test-help.h"

/* Defined for readability in tests. */
#undef UINT_MIN
#define UINT_MIN 0U

static void test_int_add_range_overflow (void);
static void test_int_sub_range_overflow (void);

int
main (void)
{
  test_int_add_range_overflow ();
  test_int_sub_range_overflow ();
  return 0;
}

static void
test_int_add_range_overflow (void)
{
  /* No overflow. */
  ASSERT (!INT_ADD_RANGE_OVERFLOW (INT_MIN, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (INT_MAX, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (INT_MIN, 1, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (INT_MAX, -1, INT_MIN, INT_MAX));
  /* a + b == b + a */
  ASSERT (!INT_ADD_RANGE_OVERFLOW (0, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (0, INT_MAX, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (1, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (-1, INT_MAX, INT_MIN, INT_MAX));

  /* Overflow. */
  ASSERT (INT_ADD_RANGE_OVERFLOW (INT_MIN, -1, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (INT_MAX, 1, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (INT_MIN, -2, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (INT_MAX, 2, INT_MIN, INT_MAX));
  /* a + b == b + a */
  ASSERT (INT_ADD_RANGE_OVERFLOW (-1, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (1, INT_MAX, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (-2, INT_MIN, INT_MIN, INT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (2, INT_MAX, INT_MIN, INT_MAX));

  /* No overflow. */
  ASSERT (!INT_ADD_RANGE_OVERFLOW (UINT_MIN, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (UINT_MAX, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (UINT_MIN, 1, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (UINT_MAX, -1, UINT_MIN, UINT_MAX));
  /* a + b == b + a */
  ASSERT (!INT_ADD_RANGE_OVERFLOW (0, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (0, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (1, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (!INT_ADD_RANGE_OVERFLOW (-1, UINT_MAX, UINT_MIN, UINT_MAX));

  /* Overflow. */
  ASSERT (INT_ADD_RANGE_OVERFLOW (UINT_MIN, -1, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (UINT_MAX, 1, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (UINT_MIN, -2, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (UINT_MAX, 2, UINT_MIN, UINT_MAX));
  /* a + b == b + a */
  ASSERT (INT_ADD_RANGE_OVERFLOW (-1, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (1, UINT_MAX, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (-2, UINT_MIN, UINT_MIN, UINT_MAX));
  ASSERT (INT_ADD_RANGE_OVERFLOW (2, UINT_MAX, UINT_MIN, UINT_MAX));
}

static void
test_int_sub_range_overflow (void)
{
  /* No overflow. */
  ASSERT (!INT_SUB_RANGE_OVERFLOW (INT_MIN, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (INT_MAX, 0, INT_MIN, INT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (INT_MIN, -1, INT_MIN, INT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (INT_MAX, 1, INT_MIN, INT_MAX));

  /* Overflow. */
  ASSERT (INT_SUB_RANGE_OVERFLOW (INT_MIN, 1, INT_MIN, INT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (INT_MAX, -1, INT_MIN, INT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (INT_MIN, 2, INT_MIN, INT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (INT_MAX, -2, INT_MIN, INT_MAX));

  /* No overflow. */
  ASSERT (!INT_SUB_RANGE_OVERFLOW (UINT_MIN, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (UINT_MAX, 0, UINT_MIN, UINT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (UINT_MIN, -1, UINT_MIN, UINT_MAX));
  ASSERT (!INT_SUB_RANGE_OVERFLOW (UINT_MAX, 1, UINT_MIN, UINT_MAX));

  /* Overflow. */
  ASSERT (INT_SUB_RANGE_OVERFLOW (UINT_MIN, 1, UINT_MIN, UINT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (UINT_MAX, -1, UINT_MIN, UINT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (UINT_MIN, 2, UINT_MIN, UINT_MAX));
  ASSERT (INT_SUB_RANGE_OVERFLOW (UINT_MAX, -2, UINT_MIN, UINT_MAX));
}
