/* -*- mode: c; -*- */

#ifndef CONFIG_H
#define CONFIG_H

#cmakedefine01 HAVE_ALLOCA_H
#cmakedefine01 HAVE_BCRYPT_H
#cmakedefine01 HAVE_CTYPE_H
#cmakedefine01 HAVE_ERROR_H
#cmakedefine01 HAVE_ERR_H
#cmakedefine01 HAVE_INTTYPES_H
#cmakedefine01 HAVE_STDINT_H
#cmakedefine01 HAVE_STDIO_H
#cmakedefine01 HAVE_STDLIB_H
#cmakedefine01 HAVE_STRINGS_H
#cmakedefine01 HAVE_STRING_H
#cmakedefine01 HAVE_SYSINFOAPI_H
#cmakedefine01 HAVE_SYS_IOCTL_H
#cmakedefine01 HAVE_SYS_RANDOM_H
#cmakedefine01 HAVE_SYS_SYSCTL_H
#cmakedefine01 HAVE_SYS_TIME_H
#cmakedefine01 HAVE_TERMIOS_H


#cmakedefine01 HAVE_TIME_H
#cmakedefine01 HAVE_UNISTD_H
#cmakedefine01 HAVE_WINDOWS_H
#cmakedefine01 HAVE_BCMP
#cmakedefine01 HAVE_BCOPY
#cmakedefine01 HAVE_BSEARCH
#cmakedefine01 HAVE_BZERO
#cmakedefine01 HAVE_CLOCK_GETTIME
#cmakedefine01 HAVE_DYSIZE
#cmakedefine01 HAVE_ENDUSERSHELL
#cmakedefine01 HAVE_ERR
#cmakedefine01 HAVE_ERRC
#cmakedefine01 HAVE_ERROR
#cmakedefine01 HAVE_ERROR_AT_LINE
#cmakedefine01 HAVE_ERROR_MESSAGE_COUNT
#cmakedefine01 HAVE_ERROR_ONE_PER_LINE
#cmakedefine01 HAVE_ERROR_PRINT_PROGNAME
#cmakedefine01 HAVE_ERRX
#cmakedefine01 HAVE_EXPLICIT_BZERO
#cmakedefine01 HAVE_FFS
#cmakedefine01 HAVE_FFSL
#cmakedefine01 HAVE_FFSLL
#cmakedefine01 HAVE_FLOCKFILE
#cmakedefine01 HAVE_FLS
#cmakedefine01 HAVE_FLSL
#cmakedefine01 HAVE_FLSLL
#cmakedefine01 HAVE_FUNLOCKFILE
#cmakedefine01 HAVE_GETCHAR_UNLOCKED
#cmakedefine01 HAVE_GETCWD
#cmakedefine01 HAVE_GETC_UNLOCKED
#cmakedefine01 HAVE_GETDELIM
#cmakedefine01 HAVE_GETEGID
#cmakedefine01 HAVE_GETENTROPY
#cmakedefine01 HAVE_GETEUID
#cmakedefine01 HAVE_GETEXECNAME
#cmakedefine01 HAVE_GETGID
#cmakedefine01 HAVE_GETLINE
#cmakedefine01 HAVE_GETPAGESIZE
#cmakedefine01 HAVE_GETPROGNAME
#cmakedefine01 HAVE_GETRANDOM
#cmakedefine01 HAVE_GETTIMEOFDAY
#cmakedefine01 HAVE_GETUID
#cmakedefine01 HAVE_GETUSERHSELL
#cmakedefine01 HAVE_GETUSERSHELL
#cmakedefine01 HAVE_INDEX
#cmakedefine01 HAVE_ISALNUM
#cmakedefine01 HAVE_ISALPHA
#cmakedefine01 HAVE_ISASCII
#cmakedefine01 HAVE_ISBLANK
#cmakedefine01 HAVE_ISCNTRL
#cmakedefine01 HAVE_ISDIGIT
#cmakedefine01 HAVE_ISGRAPH
#cmakedefine01 HAVE_ISLOWER
#cmakedefine01 HAVE_ISPRINT
#cmakedefine01 HAVE_ISPUNCT
#cmakedefine01 HAVE_ISSETUGID
#cmakedefine01 HAVE_ISSPACE
#cmakedefine01 HAVE_ISUPPER
#cmakedefine01 HAVE_ISXDIGIT
#cmakedefine01 HAVE_MEMCHR
#cmakedefine01 HAVE_MEMCMP
#cmakedefine01 HAVE_MEMCPY
#cmakedefine01 HAVE_MEMMOVE
#cmakedefine01 HAVE_MEMRCHR
#cmakedefine01 HAVE_MEMSET
#cmakedefine01 HAVE_MEMSET_EXPLICIT
#cmakedefine01 HAVE_MKDTEMP
#cmakedefine01 HAVE_MKSTEMP
#cmakedefine01 HAVE_POPCOUNT
#cmakedefine01 HAVE_POPCOUNTL
#cmakedefine01 HAVE_POPCOUNTLL
#cmakedefine01 HAVE_PROGRAM_INVOCATION_NAME
#cmakedefine01 HAVE_PROGRAM_INVOCATION_SHORT_NAME
#cmakedefine01 HAVE_PUTCHAR_UNLOCKED
#cmakedefine01 HAVE_PUTC_UNLOCKED
#cmakedefine01 HAVE_RAWMEMCHR
#cmakedefine01 HAVE_REALLOCARRAY
#cmakedefine01 HAVE_RINDEX
#cmakedefine01 HAVE_SECUREZEROMEMORY
#cmakedefine01 HAVE_SECURE_GETENV
#cmakedefine01 HAVE_SETPROGNAME
#cmakedefine01 HAVE_SETUSERSHELL
#cmakedefine01 HAVE_STPCPY
#cmakedefine01 HAVE_STRCASECMP
#cmakedefine01 HAVE_STRCAT
#cmakedefine01 HAVE_STRCHR
#cmakedefine01 HAVE_STRCHRNUL
#cmakedefine01 HAVE_STRCMP
#cmakedefine01 HAVE_STRCSPN
#cmakedefine01 HAVE_STRDUP
#cmakedefine01 HAVE_STRLEN
#cmakedefine01 HAVE_STRMODE
#cmakedefine01 HAVE_STRNCASECMP
#cmakedefine01 HAVE_STRNCAT
#cmakedefine01 HAVE_STRNCMP
#cmakedefine01 HAVE_STRNCPY
#cmakedefine01 HAVE_STRNDUP
#cmakedefine01 HAVE_STRNLEN
#cmakedefine01 HAVE_STRPBRK
#cmakedefine01 HAVE_STRRCHR
#cmakedefine01 HAVE_STRSEP
#cmakedefine01 HAVE_STRSPN
#cmakedefine01 HAVE_STRTOIMAX
#cmakedefine01 HAVE_STRTOL
#cmakedefine01 HAVE_STRTOLL
#cmakedefine01 HAVE_STRTOUL
#cmakedefine01 HAVE_STRTOULL
#cmakedefine01 HAVE_STRTOUMAX
#cmakedefine01 HAVE_SWAB
#cmakedefine01 HAVE_TIMESPEC_GET
#cmakedefine01 HAVE_TIMINGSAFE_BCMP
#cmakedefine01 HAVE_TOASCII
#cmakedefine01 HAVE_TOLOWER
#cmakedefine01 HAVE_TOUPPER
#cmakedefine01 HAVE_VERR
#cmakedefine01 HAVE_VERRC
#cmakedefine01 HAVE_VERRX
#cmakedefine01 HAVE_VWARN
#cmakedefine01 HAVE_VWARNC
#cmakedefine01 HAVE_VWARNX
#cmakedefine01 HAVE_WARN
#cmakedefine01 HAVE_WARNC
#cmakedefine01 HAVE_WARNX
#cmakedefine01 HAVE__GETCHAR_NOLOCK
#cmakedefine01 HAVE__GETC_NOLOCK
#cmakedefine01 HAVE__LOCK_FILE
#cmakedefine01 HAVE__PROGNAME
#cmakedefine01 HAVE__PUTCHAR_NOLOCK
#cmakedefine01 HAVE__PUTC_NOLOCK
#cmakedefine01 HAVE__UNLOCK_FILE
#cmakedefine01 HAVE___ARGC
#cmakedefine01 HAVE___ARGV

#cmakedefine01 HAVE_STRUCT_STAT_ST_ATIM
#cmakedefine01 HAVE_STRUCT_STAT_ST_CTIM
#cmakedefine01 HAVE_STRUCT_STAT_ST_MTIM
#cmakedefine01 HAVE_STRUCT_STAT_ST_ATIMESPEC
#cmakedefine01 HAVE_STRUCT_STAT_ST_CTIMESPEC
#cmakedefine01 HAVE_STRUCT_STAT_ST_MTIMESPEC
#cmakedefine01 HAVE_STRUCT_STAT_ST_ATIM_TIMESPEC_TV_NSEC
#cmakedefine01 HAVE_STRUCT_STAT_ST_CTIM_TIMESPEC_TV_NSEC
#cmakedefine01 HAVE_STRUCT_STAT_ST_MTIM_TIMESPEC_TV_NSEC

#endif /* CONFIG_H */
