
include_guard(GLOBAL)

# Generate <ctype.h> at libcfunk-final.cmake
set(LIBCFUNK_GENERATE_CTYPE_H "1" CACHE INTERNAL "")

check_include_file("ctype.h" HAVE_CTYPE_H)

set(LIBCFUNK_DECLARE_ISALNUM "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISALPHA "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISASCII "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISBLANK "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISCNTRL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISDIGIT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISGRAPH "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISLOWER "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISPRINT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISPUNCT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISSPACE "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISUPPER "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISXDIGIT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_TOASCII "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_TOLOWER "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_TOUPPER "0" CACHE INTERNAL "")

if (LIBCFUNK_ENABLE_TESTS)
  include($CACHE{LIBCFUNK_MODULE_DIR}/test-ctype-h.cmake)
endif ()

