
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "i686")
set(TOOLCHAIN_PREFIX "i686-linux-gnu")

find_program(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-gcc")
find_program(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}-g++")

set(CMAKE_FIND_ROOT_PATH "/usr/${TOOLCHAIN_PREFIX}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

