
set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR "i686")
set(TOOLCHAIN_PREFIX "i686-w64-mingw32")

find_program(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-gcc")
find_program(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}-g++")
find_program(WINE_PROGRAM "wine")

set(CMAKE_FIND_ROOT_PATH "/usr/${TOOLCHAIN_PREFIX}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

if (WINE_PROGRAM)
  set(CMAKE_CROSSCOMPILING_EMULATOR "${WINE_PROGRAM}")
endif ()

