
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "m68k")
set(TOOLCHAIN_PREFIX "m68k-linux-gnu")

find_program(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-gcc")
find_program(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}-g++")
find_program(QEMU_PROGRAM "qemu-m68k")

set(CMAKE_FIND_ROOT_PATH "/usr/${TOOLCHAIN_PREFIX}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

if (QEMU_PROGRAM)
  set(CMAKE_CROSSCOMPILING_EMULATOR "${QEMU_PROGRAM}")
endif ()
