
include_guard(GLOBAL)

include($CACHE{LIBCFUNK_MODULE_DIR}/sys-types-h.cmake)
include($CACHE{LIBCFUNK_MODULE_DIR}/signal-h.cmake)
include($CACHE{LIBCFUNK_MODULE_DIR}/sched-h.cmake)

# Generate <spawn.h> at libcfunk-final.cmake
set(LIBCFUNK_GENERATE_SPAWN_H "1" CACHE INTERNAL "")

check_include_file("spawn.h" HAVE_SPAWN_H)

if (HAVE_SPAWN_H)
  list(APPEND CMAKE_EXTRA_INCLUDE_FILES "spawn.h")
endif ()

list(REMOVE_DUPLICATES CMAKE_EXTRA_INCLUDE_FILES)

check_type_size("posix_spawnattr_t" POSIX_SPAWNATTR_T)
check_type_size("posix_spawn_file_actions_t" POSIX_SPAWN_FILE_ACTIONS_T)

set(LIBCFUNK_DECLARE_POSIX_SPAWN "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2 "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWN_FILE_ACTIONS_DESTROY "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWN_FILE_ACTIONS_INIT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_DESTROY "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_GETFLAGS "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_GETPGROUP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_GETSCHEDPARAM "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_GETSCHEDPOLICY "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_GETSIGDEFAULT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_GETSIGMASK "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_INIT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_SETFLAGS "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_SETPGROUP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_SETSCHEDPARAM "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_SETSCHEDPOLICY "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_SETSIGDEFAULT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNATTR_SETSIGMASK "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POSIX_SPAWNP "0" CACHE INTERNAL "")

if (LIBCFUNK_ENABLE_TESTS)
  include($CACHE{LIBCFUNK_MODULE_DIR}/test-spawn-h.cmake)
endif ()

