
include_guard(GLOBAL)

libcfunk_check_include_file("stdlib.h" HAVE_STDLIB_H)

set(LIBCFUNK_GENERATE_STDLIB_H TRUE)

set(LIBCFUNK_DECLARE_REALLOCARRAY 0)
set(LIBCFUNK_DECLARE_STRTOL 0)
set(LIBCFUNK_DECLARE_STRTOLL 0)
set(LIBCFUNK_DECLARE_STRTOUL 0)
set(LIBCFUNK_DECLARE_STRTOULL 0)
set(LIBCFUNK_DECLARE_REALLOCARRAY 0)
set(LIBCFUNK_DECLARE_SECURE_GETENV 0)
set(LIBCFUNK_DECLARE_MKSTEMP 0)
set(LIBCFUNK_DECLARE_MKDTEMP 0)
set(LIBCFUNK_DECLARE_BSEARCH 0)

