
include_guard(GLOBAL)

# Generate <stdlib.h> at libcfunk-final.cmake
set(LIBCFUNK_GENERATE_STDLIB_H "1" CACHE INTERNAL "")

check_include_file("stdlib.h" HAVE_STDLIB_H)

# Only show prototypes for checked functions.
set(LIBCFUNK_DECLARE_BSEARCH "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_MKDTEMP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_MKSTEMP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_REALLOCARRAY "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_SECURE_GETENV "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_STRTOL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_STRTOLL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_STRTOUL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_STRTOULL "0" CACHE INTERNAL "")

