
include_guard(GLOBAL)

# Generate <strings.h> at libcfunk-final.cmake
set(LIBCFUNK_GENERATE_STRINGS_H "1" CACHE INTERNAL "")

check_c_system_headers("strings.h")

# Only show prototypes for checked functions.
set(LIBCFUNK_DECLARE_BCMP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_BCOPY "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_BZERO "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_FFS "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_FFSL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_FFSLL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_FLS "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_FLSL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_FLSLL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_INDEX "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POPCOUNT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POPCOUNTL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_POPCOUNTLL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_RINDEX "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_STRCASECMP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_STRNCASECMP "0" CACHE INTERNAL "")
