
include_guard(GLOBAL)

libcfunk_check_include_file("strings.h" HAVE_STRINGS_H)

set(LIBCFUNK_GENERATE_STRINGS_H TRUE)

set(LIBCFUNK_DECLARE_FFS 0)
set(LIBCFUNK_DECLARE_FFSL 0)
set(LIBCFUNK_DECLARE_FFSLL 0)
set(LIBCFUNK_DECLARE_FLS 0)
set(LIBCFUNK_DECLARE_FLSL 0)
set(LIBCFUNK_DECLARE_FLSLL 0)
set(LIBCFUNK_DECLARE_POPCOUNT 0)
set(LIBCFUNK_DECLARE_POPCOUNTL 0)
set(LIBCFUNK_DECLARE_POPCOUNTLL 0)
set(LIBCFUNK_DECLARE_BCMP 0)
set(LIBCFUNK_DECLARE_BCOPY 0)
set(LIBCFUNK_DECLARE_BZERO 0)
set(LIBCFUNK_DECLARE_INDEX 0)
set(LIBCFUNK_DECLARE_RINDEX 0)

