
include_guard(GLOBAL)

include($CACHE{LIBCFUNK_MODULE_DIR}/fcntl-h.cmake)

# Generate <sys/socket.h> at libcfunk-final.cmake
set(LIBCFUNK_GENERATE_SYS_SOCKET_H "1" CACHE INTERNAL "")

# Headers
check_include_file("sys/socket.h" HAVE_SYS_SOCKET_H)
check_include_file("windows.h" HAVE_WINDOWS_H)
check_include_file("io.h" HAVE_IO_H)

# Check for Windows-specific headers and libraries.
if (HAVE_WINDOWS_H)
  check_include_files("windows.h;winsock2.h" HAVE_WINSOCK2_H)
  check_include_files("windows.h;ws2tcpip.h" HAVE_WS2TCPIP_H)
  find_library(WS2_32_LIBRARY "ws2_32" REQUIRED)
  target_link_libraries("$CACHE{LIBCFUNK_LIBRARY_NAME}" PUBLIC "${WS2_32_LIBRARY}")
  list(APPEND CMAKE_REQUIRED_LIBRARIES "${WS2_32_LIBRARY}")
else ()
  set(HAVE_WINSOCK2_H "" CACHE INTERNAL "")
  set(HAVE_WS2TCPIP_H "" CACHE INTERNAL "")
endif ()

set(LIBCFUNK_DECLARE_SOCKET "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ACCEPT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_BIND "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_CONNECT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_SEND "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_RECV "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_LISTEN "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETPEERNAME "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETSOCKNAME "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_SETSOCKOPT "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_SENDTO "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_RECVFROM "0" CACHE INTERNAL "")

set(LIBCFUNK_REPLACE_SOCKET "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_ACCEPT "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_BIND "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_CONNECT "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_SEND "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_RECV "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_LISTEN "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_GETPEERNAME "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_GETSOCKNAME "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_SETSOCKOPT "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_SENDTO "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_RECVFROM "0" CACHE INTERNAL "")

if (LIBCFUNK_ENABLE_TESTS)
  include($CACHE{LIBCFUNK_MODULE_DIR}/test-sys-socket-h.cmake)
endif ()

