
include_guard(GLOBAL)

libcfunk_check_include_file("unistd.h" HAVE_UNISTD_H)

set(LIBCFUNK_GENERATE_UNISTD_H TRUE)

# Hide prototypes by default.
set(LIBCFUNK_DECLARE_GETUSERSHELL 0)
set(LIBCFUNK_DECLARE_SETUSERSHELL 0)
set(LIBCFUNK_DECLARE_ENDUSERSHELL 0)
set(LIBCFUNK_DECLARE_GETCWD 0)
set(LIBCFUNK_DECLARE_SWAB 0)
set(LIBCFUNK_DECLARE_GETPAGESIZE 0)

