
include_guard(GLOBAL)

include($CACHE{LIBCFUNK_MODULE_DIR}/sys-types-h.cmake)

# Generate <unistd.h> at libcfunk-final.cmake
set(LIBCFUNK_GENERATE_UNISTD_H "1" CACHE INTERNAL "")

check_include_file("unistd.h" HAVE_UNISTD_H)
check_include_file("io.h" HAVE_IO_H)
check_include_file("direct.h" HAVE_DIRECT_H)

# Only show prototypes for checked functions.
set(LIBCFUNK_DECLARE_CHOWN "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ENDUSERSHELL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETCWD "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETPAGESIZE "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETUSERSHELL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_SETUSERSHELL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_SWAB "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETLOGIN "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETLOGIN_R "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ENVIRON "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_TTYNAME_R "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GROUP_MEMBER "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETGROUPS "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_EUIDACCESS "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_EACCESS "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_DAEMON "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_EXECL "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_EXECLE "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_EXECLP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_EXECV "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_EXECVP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_EXECVPE "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETDTABLESIZE "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_PIPE "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_ISATTY "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_SLEEP "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_GETHOSTNAME "0" CACHE INTERNAL "")
set(LIBCFUNK_DECLARE_SETHOSTNAME "0" CACHE INTERNAL "")

set(LIBCFUNK_REPLACE_GETCWD "0" CACHE INTERNAL "")
set(LIBCFUNK_REPLACE_GETHOSTNAME "0" CACHE INTERNAL "")
