
include_guard(GLOBAL)

include($CACHE{LIBCFUNK_MODULE_DIR}/stdio-h.cmake)

set(LIBCFUNK_UNLOCKED_STDIO "1" CACHE STRING "")

if (HAVE_STDIO_H)
  check_symbol_exists("clearerr_unlocked" "stdio.h" HAVE_CLEARERR_UNLOCKED)
  check_symbol_exists("feof_unlocked" "stdio.h" HAVE_FEOF_UNLOCKED)
  check_symbol_exists("ferror_unlocked" "stdio.h" HAVE_FERROR_UNLOCKED)
  check_symbol_exists("fflush_unlocked" "stdio.h" HAVE_FFLUSH_UNLOCKED)
  if (NOT HAVE_FFLUSH_UNLOCKED)
    check_symbol_exists("_fflush_nolock" "stdio.h" HAVE__FFLUSH_NOLOCK)
  endif ()
  check_symbol_exists("fgetc_unlocked" "stdio.h" HAVE_FGETC_UNLOCKED)
  if (NOT HAVE_FGETC_UNLOCKED)
    check_symbol_exists("_fgetc_nolock" "stdio.h" HAVE__FGETC_NOLOCK)
  endif ()
  check_symbol_exists("fgets_unlocked" "stdio.h" HAVE_FGETS_UNLOCKED)
  check_symbol_exists("fileno_unlocked" "stdio.h" HAVE_FILENO_UNLOCKED)
  check_symbol_exists("flockfile" "stdio.h" HAVE_FLOCKFILE)
  if (NOT HAVE_FLOCKFILE)
    check_symbol_exists("_lock_file" "stdio.h" HAVE__LOCK_FILE)
  endif ()
  check_symbol_exists("fputc_unlocked" "stdio.h" HAVE_FPUTC_UNLOCKED)
  check_symbol_exists("fputs_unlocked" "stdio.h" HAVE_FPUTS_UNLOCKED)
  check_symbol_exists("fread_unlocked" "stdio.h" HAVE_FREAD_UNLOCKED)
  if (NOT HAVE_FREAD_UNLOCKED)
    check_symbol_exists("_fread_nolock" "stdio.h" HAVE__FREAD_NOLOCK)
  endif ()
  check_symbol_exists("ftrylockfile" "stdio.h" HAVE_FTRYLOCKFILE)
  check_symbol_exists("funlockfile" "stdio.h" HAVE_FUNLOCKFILE)
  if (NOT HAVE_FUNLOCKFILE)
    check_symbol_exists("_unlock_file" "stdio.h" HAVE__UNLOCK_FILE)
  endif ()
  check_symbol_exists("fwrite_unlocked" "stdio.h" HAVE_FWRITE_UNLOCKED)
  if (NOT HAVE_FWRITE_UNLOCKED)
    check_symbol_exists("_fwrite_nolock" "stdio.h" HAVE__FWRITE_NOLOCK)
  endif ()
  check_symbol_exists("getchar_unlocked" "stdio.h" HAVE_GETCHAR_UNLOCKED)
  if (NOT HAVE_GETCHAR_UNLOCKED)
    check_symbol_exists("_getchar_nolock" "stdio.h" HAVE__GETCHAR_NOLOCK)
  endif ()
  check_symbol_exists("getc_unlocked" "stdio.h" HAVE_GETC_UNLOCKED)
  if (NOT HAVE_GETC_UNLOCKED)
    check_symbol_exists("_getc_nolock" "stdio.h" HAVE__GETC_NOLOCK)
  endif ()
  check_symbol_exists("putchar_unlocked" "stdio.h" HAVE_PUTCHAR_UNLOCKED)
  if (NOT HAVE_PUTCHAR_UNLOCKED)
    check_symbol_exists("_putchar_nolock" "stdio.h" HAVE__PUTCHAR_NOLOCK)
  endif ()
  check_symbol_exists("putc_unlocked" "stdio.h" HAVE_PUTC_UNLOCKED)
  if (NOT HAVE_PUTC_UNLOCKED)
    check_symbol_exists("_putc_nolock" "stdio.h" HAVE__PUTC_NOLOCK)
  endif ()
endif ()

