
set(CMAKE_SYSTEM_NAME "Windows")
set(TOOLCHAIN_PREFIX "x86_64-w64-mingw32")

find_program(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-gcc")
find_program(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-g++")

set(CMAKE_FIND_ROOT_PATH "/usr/${TOOLCHAIN_PREFIX}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
